__author__ = "Aaron Parsons"
__version__ = "0.0.1"

# Import first: enables JAX 64-bit mode before any JAX array is created.
from ._jax_const import DTYPE_R_JAX
from eigsep_base.const import DTYPE_R_NPY

from .basis import BeamBasis, SkyBasis
from .beam import (
    Beam,
    dipole_beam_maps_jax,
    dipole_axes_from_angles,
    v_dipole_arm_axes_jax,
    v_dipole_beam_maps_jax,
)
from .terrain import (
    HORIZON_MODELS_NPZ,
    Terrain,
    NullTerrain,
    HorizonTerrain,
)
from .observer import (
    Observer,
    EarthSurface,
    LunarSurface,
    LunarOrbitObserver,
    CircularLunarOrbit,
    EphemerisLunarOrbit,
    LunarOrbit,
)
from .ephemeris import (
    body_directions_gal,
    body_angular_radius,
    body_occulted_by_moon,
    moon_surface_intersection_mcmf,
    body_direction_from_moon_gal,
    moon_limb_cos_angle,
    earth_illuminated_fraction,
    occulted_by_moon,
    moon_surface_distance,
    moon_reflect_vector,
    sample_disk,
)
from .sources import (
    quiet_sun_temperature_K,
    solar_activity_envelope,
    sun_temperature_K,
    inject_solar_bursts,
    flag_bursts,
    earth_rfi_temperature_K,
    earth_rfi_tone_temperature_K,
    k_to_v_per_m_root_hz,
    normalized_beam_weights,
    point_source_coupling,
    point_source_signal,
    extended_source_coupling,
    extended_source_signal,
    surface_emission_signal,
    surface_residual_signal,
    synthetic_lunar_temperature_map,
    earth_rfi_signal,
    quiet_sun_signal,
)
from .reflectivity import (
    TERRAIN_TYPES,
    conductivity_from_resistivity,
    complex_permittivity,
    complex_ref_index,
    reflection_coefficient,
    eps_r_from_gpr,
    terrain_reflection_coefficient,
)
from .regolith import (
    subsolar_equilibrium_temperature_K,
    surface_equilibrium_temperature_K,
    solar_geometry,
    em_power_penetration_depth_m,
    diurnal_thermal_skin_depth_m,
    regolith_brightness_temperature_K,
    regolith_reflectivity,
    specular_reflection_direction,
    lambertian_hemisphere_weights,
)
from .sky import Sky
from .forward_model import ForwardModel, StackedForwardModel
from .calibrator import Calibrator
from .lunar import (
    LunarCampaign,
    LunarCampaignResult,
    angular_momentum_for_spin_period,
    crossed_rod_inertia,
    integrate_torque_free,
    interpolate_body_rotations,
    make_ecliptic_orbit_normals,
    normalize_vector,
)
from .lunar_recovery import LunarRecoveryAdapter
from .param_recovery import (
    DipoleBeamVarPro,
    VDipoleBeamVarPro,
    build_gsm_sky_prior,
    beam_pix_vecs,
    pack_dipole_params,
    unpack_dipole_params,
    pack_v_dipole_params,
    unpack_v_dipole_params,
    t21_matched_filter,
    t21_template,
    t21_filter_spectral,
    t21_filter_forward,
)
from .recovery import (
    AdditiveDegeneracy,
    RecoverySolution,
    ScaleDegeneracy,
    build_surface_design_matrix,
    normal_solve,
    relative_rms,
    sample_beam_weights,
    build_normal_equations,
    build_A_right_product,
    normal_solve_equations,
)

__all__ = [
    "DTYPE_R_NPY",
    "DTYPE_R_JAX",
    "BeamBasis",
    "SkyBasis",
    "Beam",
    "dipole_beam_maps_jax",
    "dipole_axes_from_angles",
    "v_dipole_beam_maps_jax",
    "v_dipole_arm_axes_jax",
    "HORIZON_MODELS_NPZ",
    "Terrain",
    "NullTerrain",
    "HorizonTerrain",
    "Observer",
    "EarthSurface",
    "LunarSurface",
    "LunarOrbitObserver",
    "CircularLunarOrbit",
    "EphemerisLunarOrbit",
    "LunarOrbit",
    "body_directions_gal",
    "body_angular_radius",
    "body_occulted_by_moon",
    "moon_surface_intersection_mcmf",
    "body_direction_from_moon_gal",
    "moon_limb_cos_angle",
    "earth_illuminated_fraction",
    "occulted_by_moon",
    "moon_surface_distance",
    "moon_reflect_vector",
    "sample_disk",
    "quiet_sun_temperature_K",
    "solar_activity_envelope",
    "sun_temperature_K",
    "inject_solar_bursts",
    "flag_bursts",
    "earth_rfi_temperature_K",
    "earth_rfi_tone_temperature_K",
    "k_to_v_per_m_root_hz",
    "normalized_beam_weights",
    "point_source_coupling",
    "point_source_signal",
    "extended_source_coupling",
    "extended_source_signal",
    "surface_emission_signal",
    "surface_residual_signal",
    "synthetic_lunar_temperature_map",
    "earth_rfi_signal",
    "quiet_sun_signal",
    "TERRAIN_TYPES",
    "conductivity_from_resistivity",
    "complex_permittivity",
    "complex_ref_index",
    "reflection_coefficient",
    "eps_r_from_gpr",
    "terrain_reflection_coefficient",
    "subsolar_equilibrium_temperature_K",
    "surface_equilibrium_temperature_K",
    "solar_geometry",
    "em_power_penetration_depth_m",
    "diurnal_thermal_skin_depth_m",
    "regolith_brightness_temperature_K",
    "regolith_reflectivity",
    "specular_reflection_direction",
    "lambertian_hemisphere_weights",
    "Sky",
    "ForwardModel",
    "StackedForwardModel",
    "Calibrator",
    "LunarCampaign",
    "LunarCampaignResult",
    "LunarRecoveryAdapter",
    "DipoleBeamVarPro",
    "VDipoleBeamVarPro",
    "build_gsm_sky_prior",
    "beam_pix_vecs",
    "pack_dipole_params",
    "unpack_dipole_params",
    "unpack_v_dipole_params",
    "pack_v_dipole_params",
    "t21_matched_filter",
    "t21_template",
    "t21_filter_spectral",
    "t21_filter_forward",
    "angular_momentum_for_spin_period",
    "AdditiveDegeneracy",
    "RecoverySolution",
    "ScaleDegeneracy",
    "build_surface_design_matrix",
    "normal_solve",
    "relative_rms",
    "sample_beam_weights",
    "build_normal_equations",
    "build_A_right_product",
    "normal_solve_equations",
    "crossed_rod_inertia",
    "integrate_torque_free",
    "interpolate_body_rotations",
    "make_ecliptic_orbit_normals",
    "normalize_vector",
]
